### ISSUE TITLE
ESPHome 2024.10.0

### ISSUE THREAD

**Issue by Xploder** [jaromeyer/mipurifier-esphome#21]
Updating to ESPHome 2024.10.0 seems to break this, the old entry in the ESPHome integration cannot be found by HA anymore and re-adding the device does work but there are no entities.

There's an EFUSE error in the log related to MAC address:
`system_api: Base MAC address from BLK3 of EFUSE version error, version = 117`

![grafik](https://github.com/user-attachments/assets/8241c714-63d5-4cda-86a9-68a4dc90d211)

Using older docker image esphome/esphome:2024.9.0, cleaning build files and re-building brings this back. Don't update.

Didn't try cleaning build files and recompiling on 2024.10.0 though, maybe worth a try.

**Comment by Nerivec** [comment]
Try with:

```yaml
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true
      ignore_efuse_custom_mac: true
```
